---
#
# Replace the place-holder <PROJECT-NAME> with your project name in lowercase letters.
#

staging:
  # Deployment path where the jar resides.
  appPath: /home/ubuntu/deployments

  # pem file location for ssh to corresponding UAT server.
  sshKeyFilePath: '/home/buynearby_staging.pem'

  # BitBucket
  bitbucketSshCredId: uat-bitbucket-cred
  bitbucketSshUrl: ssh://bitbucket.org:paynearyby/document-service.git
  repoUrl: git@bitbucket.org:paynearyby/document-service.git

  # JFrog Artifactory specific configuration.
#  jfrogArtifactId: in/nbt/aeps
  jfrogArtifactId: in/nbt/document
  jfrogLoginId: devteam@paynearby.in
  jfrogRepository: aepsv2-libs-snapshot-local
  jfrogUrl: https://paynearby.jfrog.io

  # Sonarqube specific configuration.
  sonarqubeProjectKey: aepsv2-maven-uat

  # Details for sending notification/email
  projectName: document-service
  slackChannelId: C02MQ4DG125
  teamEmailId: devteam@paynearby.in

  # Maven profile, Leave empty if no profile needs to be mentioned
  # else provide profile like below example
  #
  # mavenProfile: '-Dspring.profiles.active=dev'
  #
  mavenProfile: ''

  # Maven params, Leave empty if no params needs to be mentioned
  # else provide params like below example
  #
  # mavenProfile: '-DskipTests=true'
  #
  mavenExtraParams: '-DskipTests=true'

  # Version upgrade is in form of major.minor.patch-buildNumber
  # below versionTypes are supported, Change as per requirement:
  # - major
  # - minor
  # - patch
  # - build (Default value, will increment with each build)
  versionType: 'build'

  # Set below variable to true if only build has to happen
  build: "yes"

  # Set below variable to true if only deployment has to happen
  deploy: "yes"

  # Set both above variables to true for build and deploy in single run.


  # Mention all the modules in the project that are eligible for this CI/CD.
  # For Ex. BNB-UI should not be included as it has separate CI/CD
  supportedModules:
    - document-service



  # Mention all the modules that needs to be build/deploy as part of
  # current run of CI/CD. Mention "all" if all the modules needs to
  # be build/deploy.
  modulesToBuild:
    - document-service

production:
  jfrogRepository: aepsv2-libs-release-local
