deploy: 'yes'

deploymentEnvironment: 'PROD'

servicePort: '8899'

serviceFlags:
  - "-Dspring.profiles.active=prod"
  - "-javaagent:/opt/sfagent/sftrace/java/sftrace-java-agent.jar"
  - "-DsslCertificate=rds-combined-ca-bundle.pem"