deploy: 'yes'

deploymentEnvironment: 'PROD'

servicePort: '8899'

serviceFlags:
  - "-Xms1024M -Xmx2048M -Xmn1024M "
  - "-Dspring.profiles.active=prod"
  - "-javaagent:/opt/sfagent/sftrace/java/sftrace-java-agent.jar"
  - "-DsslCertificate=rds-combined-ca-bundle.pem"
  - "-Delastic.apm.disable_instrumentations=spring-mvc"
  - "-Delastic.apm.use_path_as_transaction_name=true"
  - "-Dsftrace.service_name=docgen"